### ISSUE TITLE
Make tab name statuses

### ISSUE THREAD

**Issue by McDKirra** [mikezimm/TrackMyTime7v2021#20]
would make more sense to have the statuses instead of how it is right now otherwise if I change back the status, I get to guess under which tab my item is under.

![image](https://user-images.githubusercontent.com/35781691/84300904-96499600-ab5b-11ea-9e74-a9ca33ad886e.png)

**Comment by mikezimm** [comment]
@McDKirra ,
Based on the latest update I just pushed (v2.2.0.0), we have some good ways to show Status which may be even better:

See details in #21 
![image](https://user-images.githubusercontent.com/49648086/105111715-8568e780-5a8f-11eb-8e39-52545415565e.png)
